version: '2'
services:
  tovserver:
    image: nmnemonic/tovserver
    ports:
      - 8080:8080
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://tov:tov@db:5432/tovserver
      - PORT=8080
  db:
    image: postgres
    environment:
      - POSTGRES_USER=tov
      - POSTGRES_PASSWORD=tov
      - POSTGRES_DB=tovserver
